name: Dependency-Track SBOM
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sbom:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install CycloneDX Generator
        run: npm install -g @cyclonedx/cyclonedx-npm

      - name: Generate SBOM
        run: cyclonedx-npm --output-file bom.json

      - name: Check SBOM file exists
        run: |
          Get-ChildItem

      - name: Upload SBOM to Dependency-Track
        run: |
         $response = curl.exe `
             -X POST "${{ secrets.DTRACK_URL }}/api/v1/bom" `
            -H "X-Api-Key: ${{ secrets.DTRACK_API_KEY }}" `
            -F "project=${{ secrets.DTRACK_PROJECT_UUID }}" `
            -F "bom=@bom.json"
          Write-Host $response
