name: Dependency-Track SBOM
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sbom:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install CycloneDX Generator
        run: npm install -g @cyclonedx/cyclonedx-npm

      - name: Generate SBOM
        run: cyclonedx-npm --output-file bom.json

      - name: Check Copyleft Licenses
        run: |

          $blocked = @(
            "GPL-2.0",
            "GPL-2.0-only",
            "GPL-3.0",
            "GPL-3.0-only",
            "AGPL-3.0-only",
            "LGPL-3.0-only"
          )

          $bom = Get-Content bom.json | ConvertFrom-Json

          foreach($c in $bom.components){

              foreach($l in $c.licenses){

                  $id = $l.license.id

                  if($blocked -contains $id){

                      Write-Host "Component: $($c.name)"
                      Write-Host "License: $id"

                      exit 1

                  }

              }

          }

          Write-Host "License policy passed."

             
      - name: Verify SBOM
        run: |
          dir
          Get-Content bom.json -TotalCount 20

      - name: Check SBOM file exists
        run: |
          Get-ChildItem

      - name: Upload SBOM to Dependency-Track
        run: |
         $response = curl.exe `
             -X POST "${{ secrets.DTRACK_URL }}/api/v1/bom" `
            -H "X-Api-Key: ${{ secrets.DTRACK_API_KEY }}" `
            -F "project=${{ secrets.DTRACK_PROJECT_UUID }}" `
            -F "bom=@bom.json"
          Write-Host $response
